name: Render a CV

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV
        run: |
          mkdir output;
          rendercv render resume.yaml --pdf-path output/resume.pdf
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: New updated resume
          tag: ${{ github.ref_name }}
          workdir: output

