name: Render a CV

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV
        run: |
          rendercv render resume.yaml --pdf-path resume.pdf
      - name: Create a Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="New updated resume" \
                resume.pdf

